### PR TITLE
Try using neon-serde to clean up the returning of complex objects

### PR DESCRIPTION
**Pull request by apendleton**
This PR experiments with using neon-serde to make serialization of a complex response cleaner. It depends upstream on a fuzzy-phrase branch that adds neon serialization derives to the requisite output types.

I think this is pretty nice. Might be worth timing it to be sure, but I'm inclined to go with this approach if we feel okay about it.

cc @aaaandrea

### CODE REVIEW

**Comment by apendleton** [comment]
I should say: we should also merge the upstream fuzzy-phrase changes before merging this one, if we choose to go with this.

**Comment by aaaandrea** [comment]
All tests pass, and the benchmarks loook to be about the same: 
```
Benchmark results:
# FuzzyPhraseSetBuilder build:
     avg FuzzyPhraseSetBuilder setup time: 6.48997ms
# FuzzyPhraseSet lookup
     avg contains() lookup time: 0.01487ms
     avg contains_prefix() lookup time: 0.00507ms
     avg fuzzy_match() lookup time: 0.09538ms
     avg fuzzy_match_prefix() lookup time: 0.10076ms
Success: All 1 benchmarks ran to completion without errors
✨  Done in 717.97s.
```

Having taken a look at `neon-serde` I think it makes sense to go this route.

**Comment by apendleton** [comment]
@aaaandrea cool, thanks for the review. This branch is currently pointed at not-master on fuzzy-phrase, since it needs some extra serialization stuff to work. We can either merge this now and have it pointed at that branch, or just wait until that stuff gets merged upstream (should go in as part of `window-weld`) and then merge the `window-weld` branch here, which includes this work -- which would you prefer?

**Comment by aaaandrea** [comment]
@apendleton Let's hold off on merging to master and merge the `window-weld` into here and then to `master` when the upstream is ready.

**Comment by apendleton** [comment]
Included in #3

**Pull request closed without merging**
