### PR TITLE
add linting support and fix eslint errors

### PR DESCRIPTION
**Pull request by amilajack**
* automatically fixed eslint errors with `eslint . --fix`
* removes unused imports
* adds eslint config

### CODE REVIEW

**Comment by apendleton** [comment]
👋 hey, thanks for your interest! This project could definitely use some linting attention, so thanks for giving that a go. If we do add an eslint config, though, we'll probably be inclined to use the same one we use for other projects within the Mapbox search team's ecosystem: https://github.com/mapbox/eslint-config-geocoding . Most notably as compared to your PR, we'll want to retain four-space indents for consistency with other search team Node projects, and with the Rust side of the house on this project specifically.

**Comment by amilajack** [comment]
Got it. Made the necessary changes

**Comment by amilajack** [comment]
@apendleton is there anything else blocking this?

**Comment by apendleton** [comment]
Nope, was just out sick. Sorry for the delay.

**Pull request merged**
